[project]
name = "autokey-wayland"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbus-python>=1.4.0",
    "evdev>=1.9.2",
    "file-magic>=0.4.1",
    "packaging>=25.0",
    "pyasyncore>=1.0.5",
    "pygobject>=3.54.5",
    "pyhamcrest>=2.1.0",
    "pyinotify>=0.9.6",
    "pyqt5>=5.15.11",
    "pystray>=0.19.5",
    "python-xlib>=0.33",
    "pyudev>=0.24.4",
    "qscintilla>=2.14.1",
    "ruff>=0.14.13",
]
